### PR TITLE
Add fitting infrastructure

### PR DESCRIPTION
**Pull request by eho-tacc**
- Add infrastructure for fitting an Episimlab model to hospital line list data, estimating a global transmission parameter like beta as the dependent variable.
- As a first pass, implement linear least squares fitting (`scipy.optimize.least_squares`) similar to [SEIR-city v1.4](https://github.com/UT-Covid/SEIR-city/blob/42e533a864f699d798314c43aaa721dbb1c50117/src/SEIRcity/fit_to_data/fitting_workflow.py)
    - Most of the v1.4 implementation is data structure munging, so the Episimlab implementation should be much more lightweight in general.
- All fitting infra will live in the new `episimlab.fit` submodule, with respective pytests at `tests/test_fit`.

### CODE REVIEW

**Comment by eho-tacc** [comment]
@kellypierce refresh my memory: I believe we want a loss function similar to [`calc_residual`](https://github.com/UT-Covid/SEIR-city/blob/42e533a864f699d798314c43aaa721dbb1c50117/src/SEIRcity/fit_to_data/fitting_workflow.py#L156). This function returns a 1-D vector of (the residual error of) Ih over the time dimension, correct?

**Comment by kellypierce** [comment]
> @kellypierce refresh my memory: I believe we want a loss function similar to [`calc_residual`](https://github.com/UT-Covid/SEIR-city/blob/42e533a864f699d798314c43aaa721dbb1c50117/src/SEIRcity/fit_to_data/fitting_workflow.py#L156). This function returns a 1-D vector of (the residual error of) Ih over the time dimension (every time point in the SEIR simulation), correct?

Yes, that is correct.

**Comment by eho-tacc** [comment]
# To Do

- [ ] [llsq](episimlab/fit/llsq.py) uses `attr` class instead of scrappy functions
- [ ] Munge compartments `Ih` and `Ih2D` from line list data `data/CV19Hospital_ICU_DeID_20210414.csv`, generating schema similar to:
```csv
date,zip_code,hosp,deceased
```

**Comment by eho-tacc** [comment]
## Takeaways from Ethan-KP Sync

- Simply ignore rows with a null discharge date
- `xslx` schema is relatively stable, but directly from hosp, so prone to change
    - Doesn't really matter, since we might want to start fitting to ICU instead of head in beds in the near future

**Comment by eho-tacc** [comment]
As of ef9a908, fitting to heads in beds summed over all vertices (zip codes).

**Pull request merged**
